# Generated by Django 3.2.4 on 2022-06-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post_emotions',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story_emotions',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
