# Generated by Django 3.2.4 on 2022-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20220613_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
