# Generated by Django 3.2.4 on 2022-06-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_story_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='story_emotions',
            name='favourite',
            field=models.IntegerField(default=0),
        ),
    ]
