# Generated by Django 3.2.4 on 2022-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220613_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story_emotions',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='indignant',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='like',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='love',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='smile',
        ),
        migrations.RemoveField(
            model_name='story_emotions',
            name='wow',
        ),
        migrations.AddField(
            model_name='story_emotions',
            name='list_emoji',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
