# Generated by Django 3.2.4 on 2022-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_story_emotions_list_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_emotions',
            name='list_emoji',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
    ]
