# Generated by Django 3.2.4 on 2022-06-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_emotions_emotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted']},
        ),
        migrations.AlterModelOptions(
            name='post_emotions',
            options={'ordering': ['-created']},
        ),
    ]
