# Generated by Django 3.2.4 on 2022-06-16 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_alter_fileupload_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commenters',
            field=models.ManyToManyField(blank=True, related_name='accept_commenters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='exception_viewer',
            field=models.ManyToManyField(blank=True, related_name='exception_viewer_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='gim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='exception_viewer',
            field=models.ManyToManyField(blank=True, related_name='exception_viewer_story', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='viewer',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='viewer',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100),
        ),
    ]
