# Generated by Django 3.2.4 on 2022-06-16 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0011_auto_20220617_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fileupload',
        ),
        migrations.CreateModel(
            name='Fileuploadpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post/')),
                ('file_preview', models.ImageField(null=True, upload_to='post/')),
                ('duration', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_post', to='post.post')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags_file', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
