# Generated by Django 3.2.4 on 2022-06-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20220617_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
