# Generated by Django 3.2.4 on 2022-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220617_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emotion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
