# Generated by Django 3.2.4 on 2022-06-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadpost',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
