# Generated by Django 3.2.4 on 2022-06-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_fileuploadpost_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hidepost',
        ),
    ]
