# Generated by Django 3.2.4 on 2022-06-26 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_delete_hidepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accept_viewer',
            field=models.ManyToManyField(blank=True, related_name='accept_viewer_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
