# Generated by Django 3.2.4 on 2022-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20220626_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewer',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='1', max_length=100),
        ),
    ]
