# Generated by Django 3.2.4 on 2022-06-29 08:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0020_filepost_emotions_reportfilepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savepost',
            new_name='Saved',
        ),
    ]
