# Generated by Django 3.2.4 on 2022-06-29 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0021_rename_savepost_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='accept_viewer',
            field=models.ManyToManyField(blank=True, related_name='accept_viewer_save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saved',
            name='viewer',
            field=models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Private'), ('5', 'Specific friends'), ('6', 'Custom'), ('7', 'Best friend'), ('8', 'Unnamed list'), ('9', 'Acquaintance')], default='4', max_length=100),
        ),
    ]
