# Generated by Django 3.2.4 on 2022-06-29 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0022_auto_20220629_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='notification',
        ),
        migrations.AddField(
            model_name='post',
            name='hide_post',
            field=models.ManyToManyField(blank=True, related_name='hide_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='turn_off_notifications',
            field=models.ManyToManyField(blank=True, related_name='turn_off_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
