# Generated by Django 3.2.4 on 2022-07-02 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0025_post_turn_off_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadpost',
            name='turn_off_file',
            field=models.ManyToManyField(blank=True, related_name='turn_off_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fileuploadpost',
            name='turn_on_file',
            field=models.ManyToManyField(blank=True, related_name='turn_on_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
