# Generated by Django 3.2.4 on 2022-06-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_profile_count_notify_unseen'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='participants',
        ),
        migrations.AddField(
            model_name='thread',
            name='emoticon',
            field=models.CharField(default='like', max_length=200),
        ),
        migrations.AddField(
            model_name='thread',
            name='theme',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_thread', to='chat.thread'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('count_read_unseen_message', models.IntegerField(default=0)),
                ('turnoff', models.CharField(max_length=100, null=True)),
                ('ignore', models.BooleanField(default=True)),
                ('blocker', models.ManyToManyField(blank=True, related_name='blocker', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_thread', to='chat.thread')),
            ],
        ),
    ]
