# Generated by Django 3.2.4 on 2022-06-20 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_thread_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='direct',
        ),
        migrations.AddField(
            model_name='thread',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
