# Generated by Django 3.2.4 on 2022-07-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0026_auto_20220702_1200'),
        ('chat', '0008_auto_20220630_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.story'),
        ),       
    ]
