# Generated by Django 3.2.4 on 2022-06-22 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20220621_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='single',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(max_length=200)),
                ('position', models.TextField(max_length=200, null=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_workplace', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('granduated', models.BooleanField(default=True)),
                ('specialized', models.TextField(max_length=1500, null=True)),
                ('degree', models.TextField(max_length=1500, null=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_university', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_relationship', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Highschool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('granduated', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=1500, null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_highschool', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('habitat_type', models.CharField(choices=[('1', 'Hometown'), ('2', 'Current city'), ('3', 'City')], max_length=100)),
                ('from_time', models.DateField(null=True)),
                ('to_time', models.DateField(null=True)),
                ('viewer', models.CharField(choices=[('1', 'Public'), ('2', 'Friend'), ('3', 'Excepttion people'), ('4', 'Specific friends'), ('5', 'Private')], default='Public', max_length=100)),
                ('exception_viewer', models.ManyToManyField(blank=True, related_name='exception_viewer_habitat', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
