# Generated by Django 3.2.4 on 2022-06-29 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0021_rename_savepost_saved'),
        ('accounts', '0008_auto_20220624_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_story',
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_post_user',
            field=models.ManyToManyField(blank=True, related_name='hide_post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_story_user',
            field=models.ManyToManyField(blank=True, related_name='hide_story_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hide_post',
            field=models.ManyToManyField(blank=True, related_name='hide_post', to='post.Post'),
        ),
    ]
