# Generated by Django 3.2.4 on 2022-06-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_emotions',
            name='indignant',
        ),
        migrations.RemoveField(
            model_name='comment_emotions',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment_emotions',
            name='love',
        ),
        migrations.RemoveField(
            model_name='comment_emotions',
            name='sad',
        ),
        migrations.RemoveField(
            model_name='comment_emotions',
            name='smile',
        ),
        migrations.RemoveField(
            model_name='comment_emotions',
            name='wow',
        ),
        migrations.AddField(
            model_name='comment_emotions',
            name='emotion',
            field=models.CharField(choices=[('1', 'like'), ('2', 'love'), ('3', 'wow'), ('4', 'sad'), ('5', 'smile'), ('6', 'indignant')], max_length=10, null=True),
        ),
    ]
