# Generated by Django 3.2.4 on 2022-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220609_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text_preview',
            field=models.TextField(null=True),
        ),
    ]
