# Generated by Django 3.2.4 on 2022-06-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20220615_2006'),
        ('comment', '0003_comment_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploadfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.fileupload'),
        ),
    ]
