# Generated by Django 3.2.4 on 2022-06-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_filepost_emotions_reportfilepost'),
        ('comment', '0004_comment_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='filepost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to='post.fileuploadpost'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post'),
        ),
    ]
