# Generated by Django 3.2.4 on 2022-06-19 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_alter_notification_text_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchcurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, max_length=90)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_serach', to=settings.AUTH_USER_MODEL)),
                ('user_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resut_seach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
