# Generated by Django 3.2.4 on 2022-06-22 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0006_searchcurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcurrent',
            name='user_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resut_seach', to=settings.AUTH_USER_MODEL),
        ),
    ]
