# Generated by Django 3.2.4 on 2022-06-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_searchcurrent_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Emotions'), (2, 'Comment'), (3, 'Follow'), (5, 'Addfriend'), (7, 'Accept friend request'), (4, 'Mentions'), (6, 'Post')]),
        ),
    ]
