# Generated by Django 3.2.4 on 2022-06-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_filepost_emotions_reportfilepost'),
        ('notifications', '0010_auto_20220627_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='filepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.fileuploadpost'),
        ),
    ]
