from django.urls import path
from . import views
from django.conf.urls import include
from .views import (
    RegisterView,
    CheckuserView,
    UserView,
    VerifyEmailView,
    SendOTPemailView,
    SendOTPphoneView,
    VerifyPhoneView,
    LoginView,
    UpdateOnline,
    Listfriend,
    FileloadAPI,
    Uploadstory,
    ListpostAPI,
    Liststoryfriend,
    StoryuserAPI,
    Actionstory,
    Storyfriend,
    Getfriendstory,
    ListEmojStory,
    ListNotifyAPI,
    Actionpost,
    Actioncomemnt,
    ListcommentAPI,
    Uploadpost,
    Profileinfo,
    SearchAPIView,
    TopsearchAPIView,
    Actionfriend,
    ActionNotification,
    ListcommentfilepostAPI,
    GetcountNotifi,
    GetcountPost,
    Getcountstory,
    FilepostAPI,
    Actionfilepost,
    Listtag
)

urlpatterns = [
    path("register", RegisterView.as_view()),
    path( "check/user", CheckuserView.as_view()),
    path( "verify/phone", VerifyPhoneView.as_view()),
    path('send-otp/email', SendOTPemailView.as_view()),
    path("verify/email", VerifyEmailView.as_view()),
    path("send-otp/phone", SendOTPphoneView.as_view()),
    path("user/friend/list", Listfriend.as_view()),
    path( "login", LoginView.as_view()),
    path( "user/info", UserView.as_view()),
    path( "user/update/online", UpdateOnline.as_view()),
    path( "file/upload", FileloadAPI.as_view()),
    path( "story/upload", Uploadstory.as_view()),
    path( "story/user", StoryuserAPI.as_view()),
    path( "story/friends", Liststoryfriend.as_view()),
    path( "story/action/<int:id>", Actionstory.as_view()),
    path( "story/friends/<int:id>", Storyfriend.as_view()),  
    path( "story/info/friends", Getfriendstory.as_view()),  
    path( "story/emotions/<int:id>", ListEmojStory.as_view()),  
    path( "notification/user", ListNotifyAPI.as_view()), 
    path( "post/list", ListpostAPI.as_view()),  
    path( "post/<int:id>", Actionpost.as_view()),  
    path( "filepost/<int:id>", Actionfilepost.as_view()), 
    
    path( "comment/<int:id>", Actioncomemnt.as_view()),  
    path( "post/<int:id>", Actionpost.as_view()), 
    path( "post/upload", Uploadpost.as_view()), 
    path( "post/comment/<int:post_id>", ListcommentAPI.as_view()), 
    path( "filepost/comment/<int:filepost_id>", ListcommentfilepostAPI.as_view()), 
    path("friend/tag",Listtag.as_view()),
    path("profile/<str:username>",Profileinfo.as_view()),
    path("search/list",SearchAPIView.as_view()),
    path("search/top/list",TopsearchAPIView.as_view()),
    path("friend/action",Actionfriend.as_view()),
    path( "notification/<int:id>", ActionNotification.as_view()), 
    path( "post/count", GetcountPost.as_view()), 
    path( "story/count", Getcountstory.as_view()), 
    path( "notification/count", GetcountNotifi.as_view()), 
    path( "photo", FilepostAPI.as_view()), 
    
    
]